<div id="location" xmlns:v="http://rdf.data-vocabulary.org/#">
   <span typeof="v:Breadcrumb">
        <a href="/<?=$this->lang->lang()?>" rel="v:url" property="v:title"><?=lang("main")?></a>
    </span> &gt; 
    <span typeof="v:Breadcrumb">
        <a href="/<?=$this->lang->lang()?>/howto" rel="v:url" property="v:title"><?=lang("howto")?></a>
    </span> &lt; 
    <span typeof="v:Breadcrumb">
        <a href="/<?=$this->lang->lang()?>/howto/formats" rel="v:url" property="v:title"><?=lang("formats")?></a>
    </span>
</div>
<table>
    <tr>
    <th><?=lang('table.format_name')?></th>
    <th><?=lang('table.extension')?></th>
    <th><?=lang('table.decoding')?></th>
    <th><?=lang('table.encoding')?></th>
    </tr>
    <tr><td>3GP2 format</td><td>3g2</td><td></td><td>&#x2713;</td></tr>
    <tr><td>3GP format</td><td>3gp</td><td></td><td>&#x2713;</td></tr>
    <tr><td>3GPP AMR file format</td><td>amr</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>4X Technologies format</td><td>4xm</td><td>&#x2713;</td><td></td></tr>
    <tr><td>8088flex TMV</td><td>tmv</td><td>&#x2713;</td><td></td></tr>
    <tr><td>A format generated by IndigoVision 8000 video server</td><td>iv8</td><td>&#x2713;</td><td></td></tr>
    <tr><td>Adobe Filmstrip</td><td>filmstrip</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>ADTS AAC</td><td>adts</td><td></td><td>&#x2713;</td></tr>
    <tr><td>ALSA audio output</td><td>alsa</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>American Laser Games MM format</td><td>mm</td><td>&#x2713;</td><td></td></tr>
    <tr><td>Apple Core Audio Format</td><td>caf</td><td>&#x2713;</td><td></td></tr>
    <tr><td>ASF format</td><td>asf</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>ASF format</td><td>asf_stream</td><td></td><td>&#x2713;</td></tr>
    <tr><td>Audio IFF</td><td>aiff</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>AVI format</td><td>avi</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>AVS format</td><td>avs</td><td>&#x2713;</td><td></td></tr>
    <tr><td>Beam Software SIFF</td><td>siff</td><td>&#x2713;</td><td></td></tr>
    <tr><td>Bethesda Softworks VID format</td><td>bethsoftvid</td><td>&#x2713;</td><td></td></tr>
    <tr><td>Bink</td><td>bink</td><td>&#x2713;</td><td></td></tr>
    <tr><td>Brute Force & Ignorance</td><td>bfi</td><td>&#x2713;</td><td></td></tr>
    <tr><td>CD Graphics Format</td><td>cdg</td><td>&#x2713;</td><td></td></tr>
    <tr><td>CRC testing format</td><td>crc</td><td></td><td>&#x2713;</td></tr>
    <tr><td>Creative Voice file format</td><td>voc</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>CRYO APC format</td><td>apc</td><td>&#x2713;</td><td></td></tr>
    <tr><td>D-Cinema audio format</td><td>daud</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>Delphine Software International CIN format</td><td>dsicin</td><td>&#x2713;</td><td></td></tr>
    <tr><td>Deluxe Paint Animation</td><td>anm</td><td>&#x2713;</td><td></td></tr>
    <tr><td>DV video format</td><td>dv</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>DV1394 A/V grab</td><td>dv1394</td><td>&#x2713;</td><td></td></tr>
    <tr><td>DXA</td><td>dxa</td><td>&#x2713;</td><td></td></tr>
    <tr><td>Electronic Arts cdata</td><td>ea_cdata</td><td>&#x2713;</td><td></td></tr>
    <tr><td>Electronic Arts Multimedia Format</td><td>ea</td><td>&#x2713;</td><td></td></tr>
    <tr><td>FFM (FFserver live feed) format</td><td>ffm</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>Flash 9 (AVM2) format</td><td>avm2</td><td></td><td>&#x2713;</td></tr>
    <tr><td>Flash format</td><td>swf</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>FLI/FLC/FLX animation format</td><td>flic</td><td>&#x2713;</td><td></td></tr>
    <tr><td>FLV format</td><td>flv</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>framecrc testing format</td><td>framecrc</td><td></td><td>&#x2713;</td></tr>
    <tr><td>Funcom ISS format</td><td>ISS</td><td>&#x2713;</td><td></td></tr>
    <tr><td>GIF Animation</td><td>gif</td><td></td><td>&#x2713;</td></tr>
    <tr><td>GXF format</td><td>gxf</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>id Cinematic format</td><td>idcin</td><td>&#x2713;</td><td></td></tr>
    <tr><td>IEC958 - S/PDIF (IEC-61937)</td><td>spdif</td><td></td><td>&#x2713;</td></tr>
    <tr><td>IFF format</td><td>IFF</td><td>&#x2713;</td><td></td></tr>
    <tr><td>image2 sequence</td><td>image2</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>Interplay C93</td><td>c93</td><td>&#x2713;</td><td></td></tr>
    <tr><td>Interplay MVE format</td><td>ipmovie</td><td>&#x2713;</td><td></td></tr>
    <tr><td>iPod H.264 MP4 format</td><td>ipod</td><td></td><td>&#x2713;</td></tr>
    <tr><td>Yamaha SMAF</td><td>mmf</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>YUV4MPEG pipe format</td><td>yuv4mpegpipe</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>lmlm4 raw format</td><td>lmlm4</td><td>&#x2713;</td><td></td></tr>
    <tr><td>Material eXchange Format</td><td>mxf</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>Material eXchange Format, D-10 Mapping</td><td>mxf_d10</td><td></td><td>&#x2713;</td></tr>
    <tr><td>Matroska file format</td><td>matroska</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>Maxis XA File Format</td><td>xa</td><td>&#x2713;</td><td></td></tr>
    <tr><td>MD STUDIO audio</td><td>aea</td><td>&#x2713;</td><td></td></tr>
    <tr><td>MIME multipart JPEG format</td><td>mpjpeg</td><td></td><td>&#x2713;</td></tr>
    <tr><td>Monkey's Audio</td><td>ape</td><td>&#x2713;</td><td></td></tr>
    <tr><td>Motion Pixels MVI format</td><td>mvi</td><td>&#x2713;</td><td></td></tr>
    <tr><td>MOV format</td><td>mov</td><td></td><td>&#x2713;</td></tr>
    <tr><td>MP4 format</td><td>mp4</td><td></td><td>&#x2713;</td></tr>
    <tr><td>MPEG audio layer 2</td><td>mp2</td><td></td><td>&#x2713;</td></tr>
    <tr><td>MPEG audio layer 3</td><td>mp3</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>MPEG-1 System format</td><td>mpeg</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>MPEG-1 System format (VCD)</td><td>vcd</td><td></td><td>&#x2713;</td></tr>
    <tr><td>MPEG-2 PS format (DVD VOB)</td><td>dvd</td><td></td><td>&#x2713;</td></tr>
    <tr><td>MPEG-2 PS format (VOB)</td><td>svcd</td><td></td><td>&#x2713;</td></tr>
    <tr><td>MPEG-2 PS format (VOB)</td><td>vob</td><td></td><td>&#x2713;</td></tr>
    <tr><td>MPEG-2 raw transport stream format</td><td>mpegtsraw</td><td>&#x2713;</td><td></td></tr>
    <tr><td>MPEG-2 transport stream format</td><td>mpegts</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>MSN TCP Webcam stream</td><td>msnwctcp</td><td>&#x2713;</td><td></td></tr>
    <tr><td>MTV format</td><td>MTV</td><td>&#x2713;</td><td></td></tr>
    <tr><td>Musepack</td><td>mpc</td><td>&#x2713;</td><td></td></tr>
    <tr><td>Musepack SV8</td><td>mpc8</td><td>&#x2713;</td><td></td></tr>
    <tr><td>NC camera feed format</td><td>nc</td><td>&#x2713;</td><td></td></tr>
    <tr><td>Nippon Telegraph and Telephone Corporation (NTT) TwinVQ</td><td>vqf</td><td>&#x2713;</td><td></td></tr>
    <tr><td>Nullsoft Streaming Video</td><td>nsv</td><td>&#x2713;</td><td></td></tr>
    <tr><td>NuppelVideo format</td><td>nuv</td><td>&#x2713;</td><td></td></tr>
    <tr><td>NUT format</td><td>nut</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>Ogg</td><td>ogg</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>Open Sound System playback</td><td>oss</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>PCM 32 bit floating-point big-endian format</td><td>f32be</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>PCM 32 bit floating-point little-endian format</td><td>f32le</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>PCM 64 bit floating-point big-endian format</td><td>f64be</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>PCM 64 bit floating-point little-endian format</td><td>f64le</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>PCM A-law format</td><td>alaw</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>PCM mu-law format</td><td>mulaw</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>PCM signed 16 bit big-endian format</td><td>s16be</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>PCM signed 16 bit little-endian format</td><td>s16le</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>PCM signed 24 bit big-endian format</td><td>s24be</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>PCM signed 24 bit little-endian format</td><td>s24le</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>PCM signed 32 bit big-endian format</td><td>s32be</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>PCM signed 32 bit little-endian format</td><td>s32le</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>PCM signed 8 bit format</td><td>08.04.11</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>PCM unsigned 16 bit big-endian format</td><td>u16be</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>PCM unsigned 16 bit little-endian format</td><td>u16le</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>PCM unsigned 24 bit big-endian format</td><td>u24be</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>PCM unsigned 24 bit little-endian format</td><td>u24le</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>PCM unsigned 32 bit big-endian format</td><td>u32be</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>PCM unsigned 32 bit little-endian format</td><td>u32le</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>PCM unsigned 8 bit format</td><td>u8</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>piped image2 sequence</td><td>image2pipe</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>Psygnosis YOP Format</td><td>yop</td><td>&#x2713;</td><td></td></tr>
    <tr><td>PSP MP4 format</td><td>psp</td><td></td><td>&#x2713;</td></tr>
    <tr><td>QCP format</td><td>qcp</td><td>&#x2713;</td><td></td></tr>
    <tr><td>QuickTime/MPEG-4/Motion JPEG 2000 format</td><td>mov,mp4,m4a,3gp,3g2,mj2</td><td>&#x2713;</td><td></td></tr>
    <tr><td>raw AC-3</td><td>ac3</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>raw ADTS AAC</td><td>aac</td><td>&#x2713;</td><td></td></tr>
    <tr><td>raw Chinese AVS video</td><td>cavsvideo</td><td>&#x2713;</td><td></td></tr>
    <tr><td>raw Dirac</td><td>dirac</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>raw DNxHD (SMPTE VC-3)</td><td>dnxhd</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>raw DTS</td><td>dts</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>raw E-AC-3</td><td>eac3</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>raw FLAC</td><td>flac</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>raw GSM</td><td>gsm</td><td>&#x2713;</td><td></td></tr>
    <tr><td>raw H.261</td><td>h261</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>raw H.263</td><td>h263</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>raw H.264 video format</td><td>h264</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>raw id RoQ format</td><td>RoQ</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>raw Ingenient MJPEG</td><td>ingenient</td><td>&#x2713;</td><td></td></tr>
    <tr><td>raw MJPEG video</td><td>mjpeg</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>raw MLP</td><td>mlp</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>raw MPEG video</td><td>mpegvideo</td><td>&#x2713;</td><td></td></tr>
    <tr><td>raw MPEG-1 video</td><td>mpeg1video</td><td></td><td>&#x2713;</td></tr>
    <tr><td>raw MPEG-2 video</td><td>mpeg2video</td><td></td><td>&#x2713;</td></tr>
    <tr><td>raw MPEG-4 video format</td><td>m4v</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>raw null video format</td><td>null</td><td></td><td>&#x2713;</td></tr>
    <tr><td>raw Shorten</td><td>shn</td><td>&#x2713;</td><td></td></tr>
    <tr><td>raw TrueHD</td><td>truehd</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>raw VC-1</td><td>vc1</td><td>&#x2713;</td><td></td></tr>
    <tr><td>raw video format</td><td>rawvideo</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>RealMedia format</td><td>rm</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>REDCODE R3D format</td><td>r3d</td><td>&#x2713;</td><td></td></tr>
    <tr><td>Renderware TeXture Dictionary</td><td>txd</td><td>&#x2713;</td><td></td></tr>
    <tr><td>RL2 format</td><td>rl2</td><td>&#x2713;</td><td></td></tr>
    <tr><td>RPL/ARMovie format</td><td>rpl</td><td>&#x2713;</td><td></td></tr>
    <tr><td>RTP output format</td><td>rtp</td><td></td><td>&#x2713;</td></tr>
    <tr><td>RTSP output format</td><td>rtsp</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>SDP</td><td>sdp</td><td>&#x2713;</td><td></td></tr>
    <tr><td>Sega FILM/CPK format</td><td>film_cpk</td><td>&#x2713;</td><td></td></tr>
    <tr><td>Sierra SOL format</td><td>sol</td><td>&#x2713;</td><td></td></tr>
    <tr><td>Sierra VMD format</td><td>vmd</td><td>&#x2713;</td><td></td></tr>
    <tr><td>Smacker video</td><td>smk</td><td>&#x2713;</td><td></td></tr>
    <tr><td>Sony OpenMG audio</td><td>oma</td><td>&#x2713;</td><td></td></tr>
    <tr><td>Sony Playstation STR format</td><td>psxstr</td><td>&#x2713;</td><td></td></tr>
    <tr><td>Sony Wave64 format</td><td>w64</td><td>&#x2713;</td><td></td></tr>
    <tr><td>SoX native format</td><td>sox</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>SSA/ASS format</td><td>ass</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>SUN AU format</td><td>au</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>TechnoTrend PVA file and stream format</td><td>pva</td><td>&#x2713;</td><td></td></tr>
    <tr><td>THP</td><td>thp</td><td>&#x2713;</td><td></td></tr>
    <tr><td>Tiertex Limited SEQ format</td><td>tiertexseq</td><td>&#x2713;</td><td></td></tr>
    <tr><td>True Audio</td><td>tta</td><td>&#x2713;</td><td></td></tr>
    <tr><td>VC-1 test bitstream</td><td>rcv</td><td></td><td>&#x2713;</td></tr>
    <tr><td>VC-1 test bitstream format</td><td>vc1test</td><td>&#x2713;</td><td></td></tr>
    <tr><td>Video4Linux device grab</td><td>video4linux</td><td>&#x2713;</td><td></td></tr>
    <tr><td>Video4Linux2 device grab</td><td>video4linux2</td><td>&#x2713;</td><td></td></tr>
    <tr><td>WAV format</td><td>wav</td><td>&#x2713;</td><td>&#x2713;</td></tr>
    <tr><td>WavPack</td><td>wv</td><td>&#x2713;</td><td></td></tr>
    <tr><td>WebM file format</td><td>webm</td><td></td><td>&#x2713;</td></tr>
    <tr><td>Westwood Studios audio format</td><td>wsaud</td><td>&#x2713;</td><td></td></tr>
    <tr><td>Westwood Studios VQA format</td><td>wsvqa</td><td>&#x2713;</td><td></td></tr>
    <tr><td>Wing Commander III movie format</td><td>wc3movie</td><td>&#x2713;</td><td></td></tr>
    <tr><td>X11grab</td><td>x11grab</td><td>&#x2713;</td><td></td></tr>
</table>