<?php
/**
 * Test class for Converter.
 * Generated by PHPUnit on 2012-10-21 at 15:04:19.
 * @group Controller
 */

class ConverterTest extends CIUnit_TestCase {

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        
        $this->CI = set_controller('converter');
    }

    /**
     * Generated from @assert ('direct', 'wap4.org') == 'http://wap4.org'.
     */
    public function testNormalize_link() {
        $this->assertEquals(
                'http://wap4.org'
                , $this->CI->normalize_link('direct', 'wap4.org')
        );
    }

    /**
     * Generated from @assert ('youtube', 'https://www.youtube.com/watch?v=-xN8Gd9TY5o&feature=g-all-u') == 'http://www.youtube.com/watch?v=-xN8Gd9TY5o'.
     */
    public function testNormalize_link2() {
        $this->assertEquals(
                'http://www.youtube.com/watch?v=-xN8Gd9TY5o'
                , $this->CI->normalize_link('youtube', 'https://www.youtube.com/watch?v=-xN8Gd9TY5o&feature=g-all-u')
        );
    }

    /**
     * @todo Implement test__destruct().
     */
    public function test__destruct() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testIs_size_within_upload_limit().
     */
    public function testIs_size_within_upload_limit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testIndex().
     */
    public function testIndex() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testLink_upload().
     */
    public function testLink_upload() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGet_web_content_length().
     */
    public function testGet_web_content_length() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testAjax_is_link_recognized().
     */
    public function testAjax_is_link_recognized() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGet_title().
     */
    public function testGet_title() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGet_extension().
     */
    public function testGet_extension() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGet_direct_extension().
     */
    public function testGet_direct_extension() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGet_direct_title().
     */
    public function testGet_direct_title() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testUpload_status().
     */
    public function testUpload_status() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testChange_settings().
     */
    public function testChange_settings() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testMobile_status().
     */
    public function testMobile_status() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testStart_converter().
     */
    public function testStart_converter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testConvert().
     */
    public function testConvert() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testConvert_status().
     */
    public function testConvert_status() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testChange_body().
     */
    public function testChange_body() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testDownload_link().
     */
    public function testDownload_link() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testPing_link().
     */
    public function testPing_link() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testWrite_fail_report().
     */
    public function testWrite_fail_report() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testRead_fail_report_into_array().
     */
    public function testRead_fail_report_into_array() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
